name: Generate Resume Formats

on:
  push:
    paths:
      - "resume.json"
      - ".github/workflows/generate-resume.yml"
      - "theme-kendall-fixed/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      RESUME_PUPPETEER_NO_SANDBOX: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      # Create a temporary directory for apt cache
      - name: Create temp apt cache directory
        run: |
          sudo mkdir -p /tmp/apt-cache
          sudo chown -R $USER:$USER /tmp/apt-cache

      - name: Cache apt packages
        id: apt-cache
        uses: actions/cache@v4
        with:
          path: /tmp/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/generate-resume.yml') }}

      # Copy cached packages if they exist
      - name: Setup apt cache
        run: |
          if [ -d "/tmp/apt-cache" ]; then
            sudo cp -r /tmp/apt-cache/* /var/cache/apt/archives/ || true
          fi

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser fonts-liberation libasound2-dev libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 xdg-utils

      # Save packages to cache
      - name: Save apt cache
        run: |
          sudo cp -r /var/cache/apt/archives/*.deb /tmp/apt-cache/ || true

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Generate HTML
        run: yarn html

      - name: Generate PDF
        run: yarn pdf

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update generated resume files"
          git push
